image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay
  SPRING_PROFILES_ACTIVE: gitlab-ci

stages:
  - test

maven_build:
  image: maven:3-jdk-8
  stage: test
  script:
    - mvn verify