image: maven:latest

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn compile -B

test:
  stage: test
  script:
    - mvn test -B

deploy:
  stage: deploy
  artifacts:
    paths:
      - target/sonnet-0.5.7-DEV.jar
  script:
    - mvn package -B
    - mvn spring-boot:run
  only:
    - master