image: maven:latest

cache:
  paths:
    - target/

build:
  stage: build
  script:
    - mvn compile -B

test:
  stage: test
  script:
    - mvn test -B

deploy:
  stage: deploy
  script:
    - mvn deploy -B
  only:
    - master