image: maven:3-jdk-8
stages:
  - build
  - test

before_script:
  - apt-get update -y && apt-get upgrade -y

cache:
  paths:
    - /root/.m2/repository/

compile:
  stage: build
  script:
    - mvn compile -B

verify:
  stage: test
  script:
    - mvn verify -B